"""Render a policy into a default-deny nftables ruleset. Only sanctioned flows get an
explicit accept; everything else falls through to `policy drop`."""
from collections import defaultdict


def generate(policy):
    by_zone = defaultdict(list)
    for d in policy.devices:
        by_zone[d.zone].append(d.ip)

    lines = [
        "#!/usr/sbin/nft -f",
        "# Generated by Technika11y kitchen-microsegmenter. Do not edit by hand.",
        "# Model: zero-trust, default-deny. Every accept below is an explicit sanctioned flow.",
        "flush ruleset",
        "",
        "table inet microseg {",
    ]

    for zone in sorted(by_zone):
        ips = ", ".join(sorted(by_zone[zone]))
        lines += [
            f"    set zone_{zone} {{",
            "        type ipv4_addr",
            f"        elements = {{ {ips} }}",
            "    }",
        ]
    lines.append("")

    lines += [
        "    chain forward {",
        "        type filter hook forward priority 0; policy drop;",
        "        ct state established,related accept",
    ]
    for fl in policy.flows:
        tag = " (audited exception)" if fl.audited_exception else ""
        comment = f"        # {fl.src_zone} -> {fl.dst_zone} :{fl.port}{tag} {fl.note}".rstrip()
        lines.append(comment)
        lines.append(
            f"        ip saddr @zone_{fl.src_zone} ip daddr @zone_{fl.dst_zone} "
            f"{fl.proto} dport {fl.port} accept"
        )
    lines += [
        "        # everything else falls through to policy drop",
        "    }",
        "}",
    ]
    return "\n".join(lines) + "\n"
